export default {
    overview: {
        name: "Barme",
        short_description: "Secteur classique de la région",
        main_activities: "Escalade Sportive",
        rock: "Calcaire",
        orientation: "E",
        altitude: "1500m",
        grades: "3b-7b",
        latitude: 46.14761,
        longitude: 6.83229,
    },
    detailed_info: {
        parking: {
            android: "https://maps.app.goo.gl/j9wNp7DUkzaUq6j49",
            ios: "-"
        },
        access: "Champéry – Grand-Paradis – Barme. La falaise, évidente, se trouve derrière les chalets et buvettes. Parking le long de la route. Falaise à 2 minutes à pied de la voiture.",
        restaurants: "Les plats des deux excellentes buvettes de Barme. Incontournable !",
        long_description: "Sur le magnifique plateau de Barme se trouve le site d’importance de la vallée d’Illiez. Lieu convivial par excellence, d’accès immédiat et offrant un large éventail de voies faciles, il accueille familles et grimpeurs de toute la Suisse romande. \nLe site se prête très bien à l’initiation et permet aussi, grâce à des voies plus techniques, de plaire aux grimpeurs expérimentés. \n\nMis en valeur par la Compagnie des Duides de Champéry et Laurent Monnet, ce site, très fréquenté, est idéal lors des fortes chaleurs d’été. \n\nIl a été progressivement rééquipé avec du matériel en inox de qualité par la Compagnie des Guides de Champéry et Hubert Caloz, puis par Frank Berrut en 2022 et 2023, suite au décès en février 2021 d’Hubert, guide charismatique et apprécié de toute la région.\n\n**Remarques**: quelques rares voies souvent humides et le secteur « Le Chat » quelque peu délaissé n’ont pas été rééquipés. La partie centrale de la falaise reste interdite à l’escalade (baume des hirondelles).",
    },    
    sector_pictures: [
        {
            path: require("@/assets/images/barme/barme_geral.png"),
            description: "Apercu general"
        },
        {
            path: require("@/assets/images/barme/barme_dents_blanches.png"),
            description: "Dents Blanches"
        },
        {
            path: require("@/assets/images/barme/barme_les_dalles.png"),
            description: "Belle Montagne et Les Dalles"
        },
        {
            path: require("@/assets/images/barme/barme_devers.png"),
            description: "Les Devers"
        },
        {
            path: require("@/assets/images/barme/barme_le_chat.png"),
            description: "Le chat"
        },
        {
            path: require("@/assets/images/barme/reequipment.png"),
            description: "Reequipment en 2023"
        },                                          
    ],
    routes: [
        {
            name: "Marguerite",
            grade: "3b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Perce-neige",
            grade: "3c",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Crocus",
            grade: "3b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "La dame du Lac",
            grade: "3b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Soldanelle",
            grade: "5a",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Primevère",
            grade: "5b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Gentiane",
            grade: "5b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Ancolie",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Welcome",
            grade: "3c",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Sanju",
            grade: "3b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Xildo",
            grade: "4a",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Sapristi",
            grade: "4a",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Crawford",
            grade: "4c",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Légerté",
            grade: "4c",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "A l'aide",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Le clan des filles",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Manu Reva",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Olive",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Y pas de blème",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Maya",
            grade: "5a, 5b",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Les jonquilles",
            grade: "4b, 5a",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Anne-Marie",
            grade: "4b, 5b",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Bernard",
            grade: "5b",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Marah",
            grade: "5a, 5c+",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Gypaète",
            grade: "4c",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Firmin le faux",
            grade: "6b",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Ne meurs pas ...",
            grade: "6a",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Dernier délai",
            grade: "5a",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Mine d'or",
            grade: "5c",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Pupuce Léa",
            grade: "6a",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Vert Onyx",
            grade: "5c",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Cabriole ",
            grade: "6a",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Pimpronelle",
            grade: "5b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Sunee door",
            grade: "5b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Aiac",
            grade: "5a",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Corsica",
            grade: "5b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Champthierry",
            grade: "6a",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "La calamite",
            grade: "7a",
            stars: 3,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Zoé",
            grade: "6b",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },     
        {
            name: "Le zèbre",
            grade: "6b",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Nébuleuse",
            grade: "6c",
            stars: 1,
            tips: "Non rééquipée",
            setter: "",
            requiped: "",
        },
        {
            name: "Radio pantoufle",
            grade: "6c+",
            stars: 2,
            tips: "De grosses prises, gros dévers",
            setter: "",
            requiped: "",
        },
        {
            name: "Un autre dindon",
            grade: "7b",
            stars: 2,
            tips: "La plus dure de la falaise",
            setter: "",
            requiped: "",
        },
        {
            name: "Antigone",
            grade: "6a+",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Clin d'œil", // get back here for photos!
            grade: "6a+",
            stars: 3,
            tips: "",
            setter: "",
            requiped: "",
            pictures: [
                {
                    path: require("@/assets/images/barme/clindoeil.png"),
                    description: "Clin d'œil",
                }
            ]            
        },
        {
            name: "Philippe là-haut",
            grade: "6c, 6c",
            stars: 3,
            tips: "2ème longueur non rééquipée",
            setter: "",
            requiped: "",
        },
        {
            name: "La savoyarde",
            grade: "6c",
            stars: 3,
            tips: "6c bien tassé (6c+?), la classique",
            setter: "",
            requiped: "",
        },
        {
            name: "Bicofilou",
            grade: "6a+",
            stars: 2,
            tips: "",
            setter: "",
            requiped: "",
        },
        {
            name: "Traversée des dieux",
            grade: "5b+",
            stars: 2,
            tips: "Départ souvent humide, utile pour mettre la corde",
            setter: "",
            requiped: "",
        },
        {
            name: "Ganymède",
            grade: "6b",
            stars: 2,
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "Science et patience",
            grade: "6b",
            stars: 1,
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "Gay pieds",
            grade: "5b",
            stars: 1,
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "Jackpot",
            grade: "6a",
            stars: 1,
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "Traquenard",
            grade: "5b",
            stars: 1,
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "L'avalanche",
            grade: "4b, 6b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "Singes roux",
            grade: "4b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "Voie non rééquipée",
        },
        {
            name: "Sicilienne",
            grade: "6b",
            stars: 1,
            tips: "",
            setter: "",
            requiped: "Voie non rééquipée",
        },                                                                                                                                                                            
    ]
};