export default {
    overview: {
        name: "Play",
        short_description: "Secteur de bloc.",
        main_activities: "Bloc",
        rock: "Calcaire",
        orientation: "N",
        altitude: "8600m",
        grades: "3A-6C",
        latitude: 46.195407,
        longitude: 6.891769,
    },
    detailed_info: {
        parking: {
            android: "https://maps.app.goo.gl/uQJWrCy9BDi9x9Jf6",
            ios: ""
        },
        access: "De Val-d'Illiez, 300 mètres après l'église, quitter la route cantonale et aller en direction du stand de tir où l'on parque. La forêt se trouve devant vous et le premier bloc se trouve 20 mètres à droite du stand.",
        restaurants: "Restaurant du tennis, et quelques restaurants aussi au centre ville.",
        long_description: "Ces dernières années, quelques «blocs» ont été brossés et fléchés. Les possibilités restent limitées, l'intérêt moyen, mais ils permettent une séance rapide à 2 pas de la voiture. Ils proposent peu de passages réellement raides. Bref, une visite si vous avez peu de temps ! À éviter lors des tirs. Terrains privés! soyez discrets.",
    },
    sector_pictures: [
        {
            path: require("@/assets/images/play/titan.jpg"),
            description: "Bloc titan"
        },
        {
            path: require("@/assets/images/play/others.jpg"),
            description: "Les autres blocs du secteur"
        },
    ],
    routes: [
        {
            id: "play_1",
            name: "Arête de gauche",
            grade: "5A",
            stars: 1,
            tips: "Départ assis",
            requiped: "",
        },
        {
            id: "play_2",
            name: "Le jeté",
            grade: "6B",
            stars: 1,
            tips: "départ idem 3",
            requiped: "",
        },
        {
            id: "play_3",
            name: "Traversée gauche-droite",
            grade: "6B+",
            stars: 3,
            tips: "Très joli",
            requiped: "",
        },
        {
            id: "play_4",
            name: "Traversée droite-gauche",
            grade: "6B+",
            stars: 1,
            tips: "",
            requiped: "",
        },
        {
            id: "play_5",
            name: "Traversée a.-r.",
            grade: "6C",
            stars: 2,
            tips: "",
            requiped: "",
        },
        {
            id: "play_6",
            name: "Premiére fissure",
            grade: "5C",
            stars: 3,
            tips: "",
            requiped: "",
        },
        {
            id: "play_7",
            name: "Deuxiéme fissure",
            grade: "5B",
            stars: 2,
            tips: "départ idem 6",
            requiped: "",
        },
        {
            id: "play_8",
            name: "Plein centre",
            grade: "?",
            stars: 1,
            tips: "Projet",
            requiped: "",
        },
        {
            id: "play_9",
            name: "La classique",
            grade: "5A",
            stars: 3,
            tips: "",
            requiped: "",
        },
        {
            id: "play_10",
            name: "Arête du milieu",
            grade: "4B",
            stars: 1,
            tips: "5B ârete seule, attention **expo**.",
            requiped: "",
        },
        {
            id: "play_11",
            name: "Plan de droite",
            grade: "5B",
            stars: 1,
            tips: "",
            requiped: "",
        },
        {
            id: "play_12",
            name: "5C bloc",
            grade: "5C",
            stars: 1,
            tips: "",
            requiped: "",
        },
        {
            id: "play_13",
            name: "3 bloc",
            grade: "3",
            stars: 1,
            tips: "",
            requiped: "",
        },
        {
            id: "play_14",
            name: "5A bloc",
            grade: "5A",
            stars: 1,
            tips: "",
            requiped: "",
        },
        {
            id: "play_15",
            name: "3 bloc",
            grade: "3",
            stars: 1,
            tips: "",
            requiped: "",
        }, 
        {
            id: "play_16",
            name: "Dalle 5A",
            grade: "5A",
            stars: 1,
            tips: "",
            requiped: "",
        },        {
            id: "play_17",
            name: "6A+ bloc",
            grade: "6A+",
            stars: 1,
            tips: "",
            requiped: "",
        },        {
            id: "play_18",
            name: "6B+ bloc",
            grade: "6B+",
            stars: 2,
            tips: "",
            requiped: "",
        }, 
    ]
};